// Generated by gencpp from file pal_supervisor_msgs/finalStartupStatusResponse.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_FINALSTARTUPSTATUSRESPONSE_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_FINALSTARTUPSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_supervisor_msgs
{
template <class ContainerAllocator>
struct finalStartupStatusResponse_
{
  typedef finalStartupStatusResponse_<ContainerAllocator> Type;

  finalStartupStatusResponse_()
    {
    }
  finalStartupStatusResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct finalStartupStatusResponse_

typedef ::pal_supervisor_msgs::finalStartupStatusResponse_<std::allocator<void> > finalStartupStatusResponse;

typedef boost::shared_ptr< ::pal_supervisor_msgs::finalStartupStatusResponse > finalStartupStatusResponsePtr;
typedef boost::shared_ptr< ::pal_supervisor_msgs::finalStartupStatusResponse const> finalStartupStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pal_supervisor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_supervisor_msgs/finalStartupStatusResponse";
  }

  static const char* value(const ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct finalStartupStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pal_supervisor_msgs::finalStartupStatusResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_FINALSTARTUPSTATUSRESPONSE_H
