// Generated by gencpp from file pal_supervisor_msgs/isAppRunningRequest.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_ISAPPRUNNINGREQUEST_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_ISAPPRUNNINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_supervisor_msgs
{
template <class ContainerAllocator>
struct isAppRunningRequest_
{
  typedef isAppRunningRequest_<ContainerAllocator> Type;

  isAppRunningRequest_()
    : appName()  {
    }
  isAppRunningRequest_(const ContainerAllocator& _alloc)
    : appName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _appName_type;
  _appName_type appName;





  typedef boost::shared_ptr< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> const> ConstPtr;

}; // struct isAppRunningRequest_

typedef ::pal_supervisor_msgs::isAppRunningRequest_<std::allocator<void> > isAppRunningRequest;

typedef boost::shared_ptr< ::pal_supervisor_msgs::isAppRunningRequest > isAppRunningRequestPtr;
typedef boost::shared_ptr< ::pal_supervisor_msgs::isAppRunningRequest const> isAppRunningRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator2> & rhs)
{
  return lhs.appName == rhs.appName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_supervisor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0659613161896351a99d743f4c69bf9";
  }

  static const char* value(const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf065961316189635ULL;
  static const uint64_t static_value2 = 0x1a99d743f4c69bf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_supervisor_msgs/isAppRunningRequest";
  }

  static const char* value(const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string appName #Name of the application \n"
;
  }

  static const char* value(const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.appName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isAppRunningRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_supervisor_msgs::isAppRunningRequest_<ContainerAllocator>& v)
  {
    s << indent << "appName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.appName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_ISAPPRUNNINGREQUEST_H
