// Generated by gencpp from file pal_supervisor_msgs/lookupTransform.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_LOOKUPTRANSFORM_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_LOOKUPTRANSFORM_H

#include <ros/service_traits.h>


#include <pal_supervisor_msgs/lookupTransformRequest.h>
#include <pal_supervisor_msgs/lookupTransformResponse.h>


namespace pal_supervisor_msgs
{

struct lookupTransform
{

typedef lookupTransformRequest Request;
typedef lookupTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lookupTransform
} // namespace pal_supervisor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_supervisor_msgs::lookupTransform > {
  static const char* value()
  {
    return "02c6b9366a79d71ff07f2dc56c230415";
  }

  static const char* value(const ::pal_supervisor_msgs::lookupTransform&) { return value(); }
};

template<>
struct DataType< ::pal_supervisor_msgs::lookupTransform > {
  static const char* value()
  {
    return "pal_supervisor_msgs/lookupTransform";
  }

  static const char* value(const ::pal_supervisor_msgs::lookupTransform&) { return value(); }
};


// service_traits::MD5Sum< ::pal_supervisor_msgs::lookupTransformRequest> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::lookupTransform >
template<>
struct MD5Sum< ::pal_supervisor_msgs::lookupTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::lookupTransform >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::lookupTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::lookupTransformRequest> should match
// service_traits::DataType< ::pal_supervisor_msgs::lookupTransform >
template<>
struct DataType< ::pal_supervisor_msgs::lookupTransformRequest>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::lookupTransform >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::lookupTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_supervisor_msgs::lookupTransformResponse> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::lookupTransform >
template<>
struct MD5Sum< ::pal_supervisor_msgs::lookupTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::lookupTransform >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::lookupTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::lookupTransformResponse> should match
// service_traits::DataType< ::pal_supervisor_msgs::lookupTransform >
template<>
struct DataType< ::pal_supervisor_msgs::lookupTransformResponse>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::lookupTransform >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::lookupTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_LOOKUPTRANSFORM_H
