// Generated by gencpp from file pal_supervisor_msgs/numberOfAnomalies.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_NUMBEROFANOMALIES_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_NUMBEROFANOMALIES_H

#include <ros/service_traits.h>


#include <pal_supervisor_msgs/numberOfAnomaliesRequest.h>
#include <pal_supervisor_msgs/numberOfAnomaliesResponse.h>


namespace pal_supervisor_msgs
{

struct numberOfAnomalies
{

typedef numberOfAnomaliesRequest Request;
typedef numberOfAnomaliesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct numberOfAnomalies
} // namespace pal_supervisor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_supervisor_msgs::numberOfAnomalies > {
  static const char* value()
  {
    return "256e37138065fcef5d440c4ba2011920";
  }

  static const char* value(const ::pal_supervisor_msgs::numberOfAnomalies&) { return value(); }
};

template<>
struct DataType< ::pal_supervisor_msgs::numberOfAnomalies > {
  static const char* value()
  {
    return "pal_supervisor_msgs/numberOfAnomalies";
  }

  static const char* value(const ::pal_supervisor_msgs::numberOfAnomalies&) { return value(); }
};


// service_traits::MD5Sum< ::pal_supervisor_msgs::numberOfAnomaliesRequest> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::numberOfAnomalies >
template<>
struct MD5Sum< ::pal_supervisor_msgs::numberOfAnomaliesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::numberOfAnomalies >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::numberOfAnomaliesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::numberOfAnomaliesRequest> should match
// service_traits::DataType< ::pal_supervisor_msgs::numberOfAnomalies >
template<>
struct DataType< ::pal_supervisor_msgs::numberOfAnomaliesRequest>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::numberOfAnomalies >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::numberOfAnomaliesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_supervisor_msgs::numberOfAnomaliesResponse> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::numberOfAnomalies >
template<>
struct MD5Sum< ::pal_supervisor_msgs::numberOfAnomaliesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::numberOfAnomalies >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::numberOfAnomaliesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::numberOfAnomaliesResponse> should match
// service_traits::DataType< ::pal_supervisor_msgs::numberOfAnomalies >
template<>
struct DataType< ::pal_supervisor_msgs::numberOfAnomaliesResponse>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::numberOfAnomalies >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::numberOfAnomaliesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_NUMBEROFANOMALIES_H
