// Generated by gencpp from file pal_supervisor_msgs/shMemIsAvailable.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMISAVAILABLE_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMISAVAILABLE_H

#include <ros/service_traits.h>


#include <pal_supervisor_msgs/shMemIsAvailableRequest.h>
#include <pal_supervisor_msgs/shMemIsAvailableResponse.h>


namespace pal_supervisor_msgs
{

struct shMemIsAvailable
{

typedef shMemIsAvailableRequest Request;
typedef shMemIsAvailableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct shMemIsAvailable
} // namespace pal_supervisor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_supervisor_msgs::shMemIsAvailable > {
  static const char* value()
  {
    return "ecf0a07e30d52a9c701ab569c846bf9a";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemIsAvailable&) { return value(); }
};

template<>
struct DataType< ::pal_supervisor_msgs::shMemIsAvailable > {
  static const char* value()
  {
    return "pal_supervisor_msgs/shMemIsAvailable";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemIsAvailable&) { return value(); }
};


// service_traits::MD5Sum< ::pal_supervisor_msgs::shMemIsAvailableRequest> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::shMemIsAvailable >
template<>
struct MD5Sum< ::pal_supervisor_msgs::shMemIsAvailableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::shMemIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::shMemIsAvailableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::shMemIsAvailableRequest> should match
// service_traits::DataType< ::pal_supervisor_msgs::shMemIsAvailable >
template<>
struct DataType< ::pal_supervisor_msgs::shMemIsAvailableRequest>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::shMemIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::shMemIsAvailableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_supervisor_msgs::shMemIsAvailableResponse> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::shMemIsAvailable >
template<>
struct MD5Sum< ::pal_supervisor_msgs::shMemIsAvailableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::shMemIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::shMemIsAvailableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::shMemIsAvailableResponse> should match
// service_traits::DataType< ::pal_supervisor_msgs::shMemIsAvailable >
template<>
struct DataType< ::pal_supervisor_msgs::shMemIsAvailableResponse>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::shMemIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::shMemIsAvailableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMISAVAILABLE_H
