// Generated by gencpp from file pal_supervisor_msgs/shMemGetUserIdResponse.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMGETUSERIDRESPONSE_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMGETUSERIDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_supervisor_msgs
{
template <class ContainerAllocator>
struct shMemGetUserIdResponse_
{
  typedef shMemGetUserIdResponse_<ContainerAllocator> Type;

  shMemGetUserIdResponse_()
    : userId()  {
    }
  shMemGetUserIdResponse_(const ContainerAllocator& _alloc)
    : userId(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _userId_type;
  _userId_type userId;





  typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct shMemGetUserIdResponse_

typedef ::pal_supervisor_msgs::shMemGetUserIdResponse_<std::allocator<void> > shMemGetUserIdResponse;

typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdResponse > shMemGetUserIdResponsePtr;
typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdResponse const> shMemGetUserIdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.userId == rhs.userId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_supervisor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "312d2f7aff7c95ea4de64a64f8265bbd";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x312d2f7aff7c95eaULL;
  static const uint64_t static_value2 = 0x4de64a64f8265bbdULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_supervisor_msgs/shMemGetUserIdResponse";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string userId #Returns the user ID related to the Shared memory\n"
"\n"
;
  }

  static const char* value(const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.userId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shMemGetUserIdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_supervisor_msgs::shMemGetUserIdResponse_<ContainerAllocator>& v)
  {
    s << indent << "userId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.userId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMGETUSERIDRESPONSE_H
