// Generated by gencpp from file pal_supervisor_msgs/shMemIsClosedResponse.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMISCLOSEDRESPONSE_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMISCLOSEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_supervisor_msgs
{
template <class ContainerAllocator>
struct shMemIsClosedResponse_
{
  typedef shMemIsClosedResponse_<ContainerAllocator> Type;

  shMemIsClosedResponse_()
    : isClosed(false)  {
    }
  shMemIsClosedResponse_(const ContainerAllocator& _alloc)
    : isClosed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isClosed_type;
  _isClosed_type isClosed;





  typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct shMemIsClosedResponse_

typedef ::pal_supervisor_msgs::shMemIsClosedResponse_<std::allocator<void> > shMemIsClosedResponse;

typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemIsClosedResponse > shMemIsClosedResponsePtr;
typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemIsClosedResponse const> shMemIsClosedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isClosed == rhs.isClosed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_supervisor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47103612e358fb97f8ed773bb47d8e60";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47103612e358fb97ULL;
  static const uint64_t static_value2 = 0xf8ed773bb47d8e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_supervisor_msgs/shMemIsClosedResponse";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isClosed #True if the sharedMemory with the given key has been closed\n"
"\n"
;
  }

  static const char* value(const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isClosed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shMemIsClosedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_supervisor_msgs::shMemIsClosedResponse_<ContainerAllocator>& v)
  {
    s << indent << "isClosed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isClosed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMISCLOSEDRESPONSE_H
