// Generated by gencpp from file pal_supervisor_msgs/shMemGetUserIdRequest.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMGETUSERIDREQUEST_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMGETUSERIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_supervisor_msgs
{
template <class ContainerAllocator>
struct shMemGetUserIdRequest_
{
  typedef shMemGetUserIdRequest_<ContainerAllocator> Type;

  shMemGetUserIdRequest_()
    : appName()
    , key(0)  {
    }
  shMemGetUserIdRequest_(const ContainerAllocator& _alloc)
    : appName(_alloc)
    , key(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _appName_type;
  _appName_type appName;

   typedef int32_t _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct shMemGetUserIdRequest_

typedef ::pal_supervisor_msgs::shMemGetUserIdRequest_<std::allocator<void> > shMemGetUserIdRequest;

typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdRequest > shMemGetUserIdRequestPtr;
typedef boost::shared_ptr< ::pal_supervisor_msgs::shMemGetUserIdRequest const> shMemGetUserIdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.appName == rhs.appName &&
    lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_supervisor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90459c82875202e256f0669058e774a2";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90459c82875202e2ULL;
  static const uint64_t static_value2 = 0x56f0669058e774a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_supervisor_msgs/shMemGetUserIdRequest";
  }

  static const char* value(const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string appName #Name of the application sending the command\n"
"int32 key #Shared memory Key\n"
;
  }

  static const char* value(const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.appName);
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shMemGetUserIdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_supervisor_msgs::shMemGetUserIdRequest_<ContainerAllocator>& v)
  {
    s << indent << "appName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.appName);
    s << indent << "key: ";
    Printer<int32_t>::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_SHMEMGETUSERIDREQUEST_H
