// Generated by gencpp from file pal_supervisor_msgs/supervisorIsAvailable.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_SUPERVISORISAVAILABLE_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_SUPERVISORISAVAILABLE_H

#include <ros/service_traits.h>


#include <pal_supervisor_msgs/supervisorIsAvailableRequest.h>
#include <pal_supervisor_msgs/supervisorIsAvailableResponse.h>


namespace pal_supervisor_msgs
{

struct supervisorIsAvailable
{

typedef supervisorIsAvailableRequest Request;
typedef supervisorIsAvailableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisorIsAvailable
} // namespace pal_supervisor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailable > {
  static const char* value()
  {
    return "efb9ac7739f299decb8575015d81760c";
  }

  static const char* value(const ::pal_supervisor_msgs::supervisorIsAvailable&) { return value(); }
};

template<>
struct DataType< ::pal_supervisor_msgs::supervisorIsAvailable > {
  static const char* value()
  {
    return "pal_supervisor_msgs/supervisorIsAvailable";
  }

  static const char* value(const ::pal_supervisor_msgs::supervisorIsAvailable&) { return value(); }
};


// service_traits::MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailableRequest> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailable >
template<>
struct MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::supervisorIsAvailableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::supervisorIsAvailableRequest> should match
// service_traits::DataType< ::pal_supervisor_msgs::supervisorIsAvailable >
template<>
struct DataType< ::pal_supervisor_msgs::supervisorIsAvailableRequest>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::supervisorIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::supervisorIsAvailableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailableResponse> should match
// service_traits::MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailable >
template<>
struct MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_supervisor_msgs::supervisorIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::supervisorIsAvailableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_supervisor_msgs::supervisorIsAvailableResponse> should match
// service_traits::DataType< ::pal_supervisor_msgs::supervisorIsAvailable >
template<>
struct DataType< ::pal_supervisor_msgs::supervisorIsAvailableResponse>
{
  static const char* value()
  {
    return DataType< ::pal_supervisor_msgs::supervisorIsAvailable >::value();
  }
  static const char* value(const ::pal_supervisor_msgs::supervisorIsAvailableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_SUPERVISORISAVAILABLE_H
