// Generated by gencpp from file pal_supervisor_msgs/tcpIpIsAvailableResponse.msg
// DO NOT EDIT!


#ifndef PAL_SUPERVISOR_MSGS_MESSAGE_TCPIPISAVAILABLERESPONSE_H
#define PAL_SUPERVISOR_MSGS_MESSAGE_TCPIPISAVAILABLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_supervisor_msgs
{
template <class ContainerAllocator>
struct tcpIpIsAvailableResponse_
{
  typedef tcpIpIsAvailableResponse_<ContainerAllocator> Type;

  tcpIpIsAvailableResponse_()
    : available(false)
    , suggestedSleepTime(0)  {
    }
  tcpIpIsAvailableResponse_(const ContainerAllocator& _alloc)
    : available(false)
    , suggestedSleepTime(0)  {
  (void)_alloc;
    }



   typedef uint8_t _available_type;
  _available_type available;

   typedef uint32_t _suggestedSleepTime_type;
  _suggestedSleepTime_type suggestedSleepTime;





  typedef boost::shared_ptr< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct tcpIpIsAvailableResponse_

typedef ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<std::allocator<void> > tcpIpIsAvailableResponse;

typedef boost::shared_ptr< ::pal_supervisor_msgs::tcpIpIsAvailableResponse > tcpIpIsAvailableResponsePtr;
typedef boost::shared_ptr< ::pal_supervisor_msgs::tcpIpIsAvailableResponse const> tcpIpIsAvailableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.available == rhs.available &&
    lhs.suggestedSleepTime == rhs.suggestedSleepTime;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator1> & lhs, const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_supervisor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ddb387405b8e9e09b259cdcaafeb09a";
  }

  static const char* value(const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ddb387405b8e9e0ULL;
  static const uint64_t static_value2 = 0x9b259cdcaafeb09aULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_supervisor_msgs/tcpIpIsAvailableResponse";
  }

  static const char* value(const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool available #True if the TCP Server is available, false if it's not\n"
"uint32 suggestedSleepTime #Ms suggested to the client to sleep before trying again\n"
"\n"
;
  }

  static const char* value(const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.available);
      stream.next(m.suggestedSleepTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tcpIpIsAvailableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_supervisor_msgs::tcpIpIsAvailableResponse_<ContainerAllocator>& v)
  {
    s << indent << "available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.available);
    s << indent << "suggestedSleepTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.suggestedSleepTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_SUPERVISOR_MSGS_MESSAGE_TCPIPISAVAILABLERESPONSE_H
