planners:
  - name: NavfnROS
    type: navfn/NavfnROS     
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner

controllers:
  - name: PalLocalPlanner
    type: pal_local_planner/PalLocalPlanner
  - name: TebLocalPlannerROS
    type: teb_local_planner/TebLocalPlannerROS

planner_frequency: 2.0
planner_patience : 4.0
planner_max_retries: 2

controller_frequency: 10.0
controller_patience : 10.0

oscillation_timeout : 10.0
oscillation_distance:  0.2

recovery_enabled: true
recovery_patience: 50.0
