services:
  ros1_rob_tiago:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ipc: host
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - ${XAUTHORITY:-0}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./carpeta_compartida:/home/tiago/carpeta_compartida
      - /dev:/dev
    devices:
      - /dev/dri:/dev/dri
    tmpfs:
      - /dev/shm:rw