(cl:defpackage pal_composite_navigation_msgs-msg
  (:use )
  (:export
   "<GOTOFLOORPOIACTION>"
   "GOTOFLOORPOIACTION"
   "<GOTOFLOORPOIACTIONFEEDBACK>"
   "GOTOFLOORPOIACTIONFEEDBACK"
   "<GOTOFLOORPOIACTIONGOAL>"
   "GOTOFLOORPOIACTIONGOAL"
   "<GOTOFLOORPOIACTIONRESULT>"
   "GOTOFLOORPOIACTIONRESULT"
   "<GOTOFLOORPOIFEEDBACK>"
   "GOTOFLOORPOIFEEDBACK"
   "<GOTOFLOORPOIGOAL>"
   "GOTOFLOORPOIGOAL"
   "<GOTOFLOORPOIRESULT>"
   "GOTOFLOORPOIRESULT"
  ))

