; Auto-generated. Do not edit!


(cl:in-package pal_composite_navigation_msgs-msg)


;//! \htmlinclude GoToFloorPOIResult.msg.html

(cl:defclass <GoToFloorPOIResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GoToFloorPOIResult (<GoToFloorPOIResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToFloorPOIResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToFloorPOIResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_composite_navigation_msgs-msg:<GoToFloorPOIResult> is deprecated: use pal_composite_navigation_msgs-msg:GoToFloorPOIResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToFloorPOIResult>) ostream)
  "Serializes a message object of type '<GoToFloorPOIResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToFloorPOIResult>) istream)
  "Deserializes a message object of type '<GoToFloorPOIResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToFloorPOIResult>)))
  "Returns string type for a message object of type '<GoToFloorPOIResult>"
  "pal_composite_navigation_msgs/GoToFloorPOIResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToFloorPOIResult)))
  "Returns string type for a message object of type 'GoToFloorPOIResult"
  "pal_composite_navigation_msgs/GoToFloorPOIResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToFloorPOIResult>)))
  "Returns md5sum for a message object of type '<GoToFloorPOIResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToFloorPOIResult)))
  "Returns md5sum for a message object of type 'GoToFloorPOIResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToFloorPOIResult>)))
  "Returns full string definition for message of type '<GoToFloorPOIResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToFloorPOIResult)))
  "Returns full string definition for message of type 'GoToFloorPOIResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToFloorPOIResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToFloorPOIResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToFloorPOIResult
))
