// Auto-generated. Do not edit!

// (in-package corridor_exploration_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class CorridorExplorationFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.state = null;
    }
    else {
      if (initObj.hasOwnProperty('state')) {
        this.state = initObj.state
      }
      else {
        this.state = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CorridorExplorationFeedback
    // Serialize message field [state]
    bufferOffset = std_msgs.msg.String.serialize(obj.state, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CorridorExplorationFeedback
    let len;
    let data = new CorridorExplorationFeedback(null);
    // Deserialize message field [state]
    data.state = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.state);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'corridor_exploration_msgs/CorridorExplorationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '00f454ac92e74bc45c1c81b3a97a4546';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback definition
    std_msgs/String state
    
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CorridorExplorationFeedback(null);
    if (msg.state !== undefined) {
      resolved.state = std_msgs.msg.String.Resolve(msg.state)
    }
    else {
      resolved.state = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = CorridorExplorationFeedback;
