// Auto-generated. Do not edit!

// (in-package corridor_exploration_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class CorridorExplorationGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_poi = null;
    }
    else {
      if (initObj.hasOwnProperty('target_poi')) {
        this.target_poi = initObj.target_poi
      }
      else {
        this.target_poi = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CorridorExplorationGoal
    // Serialize message field [target_poi]
    bufferOffset = std_msgs.msg.String.serialize(obj.target_poi, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CorridorExplorationGoal
    let len;
    let data = new CorridorExplorationGoal(null);
    // Deserialize message field [target_poi]
    data.target_poi = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.target_poi);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'corridor_exploration_msgs/CorridorExplorationGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ea18c894eff4a41f4b89b7dd4cbd5c56';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    std_msgs/String target_poi
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CorridorExplorationGoal(null);
    if (msg.target_poi !== undefined) {
      resolved.target_poi = std_msgs.msg.String.Resolve(msg.target_poi)
    }
    else {
      resolved.target_poi = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = CorridorExplorationGoal;
