link_list: ['arm_left_4_link',
            'arm_left_7_link',
            'hand_left_thumb_link',
            'hand_left_index_1_link',
            'hand_left_index_3_link',
            'arm_right_4_link',
            'arm_right_7_link',
            'hand_right_thumb_link',
            'hand_right_index_1_link',
            'hand_right_index_3_link',
            'base_bumper_01_link',
            'base_bumper_02_link',
            'base_sonar_01_link',
            'base_sonar_02_link',
            'base_sonar_03_link',
            'base_sonar_04_link',
            'base_sonar_05_link',
            'base_sonar_06_link',
            'base_sonar_07_link',
            'base_sonar_08_link',
            'base_sonar_09_link',
            'base_sonar_10_link',
            'base_sonar_11_link',
            'base_sonar_12_link']
padding: 0.04
