// Generated by gencpp from file corridor_exploration_msgs/CorridorExplorationResult.msg
// DO NOT EDIT!


#ifndef CORRIDOR_EXPLORATION_MSGS_MESSAGE_CORRIDOREXPLORATIONRESULT_H
#define CORRIDOR_EXPLORATION_MSGS_MESSAGE_CORRIDOREXPLORATIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>
#include <std_msgs/String.h>

namespace corridor_exploration_msgs
{
template <class ContainerAllocator>
struct CorridorExplorationResult_
{
  typedef CorridorExplorationResult_<ContainerAllocator> Type;

  CorridorExplorationResult_()
    : reached()
    , message()  {
    }
  CorridorExplorationResult_(const ContainerAllocator& _alloc)
    : reached(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _reached_type;
  _reached_type reached;

   typedef  ::std_msgs::String_<ContainerAllocator>  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> const> ConstPtr;

}; // struct CorridorExplorationResult_

typedef ::corridor_exploration_msgs::CorridorExplorationResult_<std::allocator<void> > CorridorExplorationResult;

typedef boost::shared_ptr< ::corridor_exploration_msgs::CorridorExplorationResult > CorridorExplorationResultPtr;
typedef boost::shared_ptr< ::corridor_exploration_msgs::CorridorExplorationResult const> CorridorExplorationResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator1> & lhs, const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator2> & rhs)
{
  return lhs.reached == rhs.reached &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator1> & lhs, const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corridor_exploration_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d210301fb84a541ab3ae1d0d10f9358";
  }

  static const char* value(const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d210301fb84a541ULL;
  static const uint64_t static_value2 = 0xab3ae1d0d10f9358ULL;
};

template<class ContainerAllocator>
struct DataType< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corridor_exploration_msgs/CorridorExplorationResult";
  }

  static const char* value(const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"std_msgs/Bool reached\n"
"std_msgs/String message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CorridorExplorationResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corridor_exploration_msgs::CorridorExplorationResult_<ContainerAllocator>& v)
  {
    s << indent << "reached: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.reached);
    s << indent << "message: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORRIDOR_EXPLORATION_MSGS_MESSAGE_CORRIDOREXPLORATIONRESULT_H
