// Generated by gencpp from file corridor_exploration_msgs/GetPoseRequest.msg
// DO NOT EDIT!


#ifndef CORRIDOR_EXPLORATION_MSGS_MESSAGE_GETPOSEREQUEST_H
#define CORRIDOR_EXPLORATION_MSGS_MESSAGE_GETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace corridor_exploration_msgs
{
template <class ContainerAllocator>
struct GetPoseRequest_
{
  typedef GetPoseRequest_<ContainerAllocator> Type;

  GetPoseRequest_()
    : mode(0)
    , pose()
    , yaw(0.0)  {
    }
  GetPoseRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , pose(_alloc)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _yaw_type;
  _yaw_type yaw;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GUESS)
  #undef GUESS
#endif
#if defined(_WIN32) && defined(IDENTITY)
  #undef IDENTITY
#endif
#if defined(_WIN32) && defined(DIRECTION)
  #undef DIRECTION
#endif

  enum {
    GUESS = 1u,
    IDENTITY = 2u,
    DIRECTION = 3u,
  };


  typedef boost::shared_ptr< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseRequest_

typedef ::corridor_exploration_msgs::GetPoseRequest_<std::allocator<void> > GetPoseRequest;

typedef boost::shared_ptr< ::corridor_exploration_msgs::GetPoseRequest > GetPoseRequestPtr;
typedef boost::shared_ptr< ::corridor_exploration_msgs::GetPoseRequest const> GetPoseRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator1> & lhs, const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.pose == rhs.pose &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator1> & lhs, const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace corridor_exploration_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fa69d3c08ca045faf630732718097fe";
  }

  static const char* value(const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fa69d3c08ca045fULL;
  static const uint64_t static_value2 = 0xaf630732718097feULL;
};

template<class ContainerAllocator>
struct DataType< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "corridor_exploration_msgs/GetPoseRequest";
  }

  static const char* value(const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request\n"
"#Mode actions\n"
"uint8 GUESS = 1\n"
"uint8 IDENTITY = 2\n"
"uint8 DIRECTION = 3\n"
"uint8 mode\n"
"geometry_msgs/PoseStamped pose\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.pose);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::corridor_exploration_msgs::GetPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORRIDOR_EXPLORATION_MSGS_MESSAGE_GETPOSEREQUEST_H
