// Generated by gencpp from file corridor_exploration_msgs/GetPose.msg
// DO NOT EDIT!


#ifndef CORRIDOR_EXPLORATION_MSGS_MESSAGE_GETPOSE_H
#define CORRIDOR_EXPLORATION_MSGS_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <corridor_exploration_msgs/GetPoseRequest.h>
#include <corridor_exploration_msgs/GetPoseResponse.h>


namespace corridor_exploration_msgs
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace corridor_exploration_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::corridor_exploration_msgs::GetPose > {
  static const char* value()
  {
    return "7698893db06037c46b550b3265c90d88";
  }

  static const char* value(const ::corridor_exploration_msgs::GetPose&) { return value(); }
};

template<>
struct DataType< ::corridor_exploration_msgs::GetPose > {
  static const char* value()
  {
    return "corridor_exploration_msgs/GetPose";
  }

  static const char* value(const ::corridor_exploration_msgs::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::corridor_exploration_msgs::GetPoseRequest> should match
// service_traits::MD5Sum< ::corridor_exploration_msgs::GetPose >
template<>
struct MD5Sum< ::corridor_exploration_msgs::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::corridor_exploration_msgs::GetPose >::value();
  }
  static const char* value(const ::corridor_exploration_msgs::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::corridor_exploration_msgs::GetPoseRequest> should match
// service_traits::DataType< ::corridor_exploration_msgs::GetPose >
template<>
struct DataType< ::corridor_exploration_msgs::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::corridor_exploration_msgs::GetPose >::value();
  }
  static const char* value(const ::corridor_exploration_msgs::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::corridor_exploration_msgs::GetPoseResponse> should match
// service_traits::MD5Sum< ::corridor_exploration_msgs::GetPose >
template<>
struct MD5Sum< ::corridor_exploration_msgs::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::corridor_exploration_msgs::GetPose >::value();
  }
  static const char* value(const ::corridor_exploration_msgs::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::corridor_exploration_msgs::GetPoseResponse> should match
// service_traits::DataType< ::corridor_exploration_msgs::GetPose >
template<>
struct DataType< ::corridor_exploration_msgs::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::corridor_exploration_msgs::GetPose >::value();
  }
  static const char* value(const ::corridor_exploration_msgs::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORRIDOR_EXPLORATION_MSGS_MESSAGE_GETPOSE_H
