# MapperSensorManager:
scan_buffer_maximum_scan_distance: 10 # default: 20
scan_buffer_size                 : 60 # default: # 80 ~= scan_buffer_max_scan_dist / min_travel_dist

# Loop Closing:
loop_search_maximum_distance        : 10.0          # default: 10
loop_search_maximum_angular_distance: 1.570796327   # default: pi/2
loop_search_minimum_graph_distance  : 10            # default: 10
loop_match_maximum_variance_coarse  : 0.9           # default: 0.16
loop_match_minimum_chain_size       : 10            # default: 4
loop_match_minimum_response_coarse  : 0.8           # default: 0.8
loop_match_minimum_response_fine    : 0.9           # default: 0.95
loop_search_space_dimension         : 5.0           # default: 8
loop_search_space_resolution        : 0.05          # default: 0.05 we were using 0.01
loop_search_space_smear_deviation   : 0.03          # default: 0.03
link_match_minimum_response_fine    : 0.4           # default: 0.8
link_scan_maximum_distance          : 8.0           # default: 10.0

restore_defaults: false

transform_publish_period: 0.05
pose_publish_period     : 1.0
mapper_period           : 0.05
map_update_period       : 1.0

# Listed below pal_karto default params
# Any one of them can be overloaded for each
# robot directly in {ROBOT}_2dnav/config/mapping/karto.yaml

# range_threshold: 49
# use_scan_barycenter: true
# minimum_travel_distance: 0.2
# minimum_travel_heading:  0.174532925 # pi/18
# map_free_space: false

# autostart                 : true
# odom_frame                : odom
# map_frame                 : map
# base_frame                : base_link
# throttle_scans            : 1
# max_scan_queue_size       : 30
# acceptable_scan_queue_size: 0         #if queue full, wait until it gets empty before the robot can move again
# resolution                : 0.05      #map cells resolution, local costmap resolution should be set accordingly
# trajectory_file           :
# transformation_tolerance  : 0.2

# The following are defined in scan_matcher.yaml

# Scan Matcher:
# use_scan_matching                : true
# distance_variance_penalty        : 0.3
# angle_variance_penalty           : 0.121839781
# fine_search_angle_offset         : 0.00349066 # 0.2 rad
# coarse_search_angle_offset       : 0.34906585 # 20 rad
# coarse_angle_resolution          : 0.03490659 # 2 rad
# minimum_angle_penalty            : 0.9
# minimum_distance_penalty         : 0.5
# use_response_expansion           : false

# Correlation:
# correlation_search_space_dimension      : 0.3
# correlation_search_space_resolution     : 0.01
# correlation_search_space_smear_deviation: 0.03
