# Scan Matcher:
use_scan_matching                : true
distance_variance_penalty        : 0.3
angle_variance_penalty           : 0.121839781
fine_search_angle_offset         : 0.00349066 # 0.2 rad
coarse_search_angle_offset       : 0.34906585 # 20 rad
coarse_angle_resolution          : 0.03490659 # 2 rad
minimum_angle_penalty            : 0.9
minimum_distance_penalty         : 0.5
use_response_expansion           : false

# Correlation:
correlation_search_space_dimension      : 0.3
correlation_search_space_resolution     : 0.01
correlation_search_space_smear_deviation: 0.03

