#Request
#Mode actions
uint8 GUESS = 1
uint8 IDENTITY = 2
uint8 DIRECTION = 3
uint8 mode
geometry_msgs/PoseStamped pose
float64 yaw
---
#Response

geometry_msgs/PoseStamped pose
std_msgs/String message
std_msgs/Bool is_open_space
std_msgs/Bool success

