// Generated by gencpp from file pal_composite_navigation_msgs/GoToFloorPOIFeedback.msg
// DO NOT EDIT!


#ifndef PAL_COMPOSITE_NAVIGATION_MSGS_MESSAGE_GOTOFLOORPOIFEEDBACK_H
#define PAL_COMPOSITE_NAVIGATION_MSGS_MESSAGE_GOTOFLOORPOIFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_composite_navigation_msgs
{
template <class ContainerAllocator>
struct GoToFloorPOIFeedback_
{
  typedef GoToFloorPOIFeedback_<ContainerAllocator> Type;

  GoToFloorPOIFeedback_()
    {
    }
  GoToFloorPOIFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GoToFloorPOIFeedback_

typedef ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<std::allocator<void> > GoToFloorPOIFeedback;

typedef boost::shared_ptr< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback > GoToFloorPOIFeedbackPtr;
typedef boost::shared_ptr< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback const> GoToFloorPOIFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pal_composite_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_composite_navigation_msgs/GoToFloorPOIFeedback";
  }

  static const char* value(const ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
;
  }

  static const char* value(const ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToFloorPOIFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pal_composite_navigation_msgs::GoToFloorPOIFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PAL_COMPOSITE_NAVIGATION_MSGS_MESSAGE_GOTOFLOORPOIFEEDBACK_H
