(cl:defpackage pal_waypoint_msgs-msg
  (:use )
  (:export
   "<DOWAYPOINTNAVIGATIONACTION>"
   "DOWAYPOINTNAVIGATIONACTION"
   "<DOWAYPOINTNAVIGATIONACTIONFEEDBACK>"
   "DOWAYPOINTNAVIGATIONACTIONFEEDBACK"
   "<DOWAYPOINTNAVIGATIONACTIONGOAL>"
   "DOWAYPOINTNAVIGATIONACTIONGOAL"
   "<DOWAYPOINTNAVIGATIONACTIONRESULT>"
   "DOWAYPOINTNAVIGATIONACTIONRESULT"
   "<DOWAYPOINTNAVIGATIONFEEDBACK>"
   "DOWAYPOINTNAVIGATIONFEEDBACK"
   "<DOWAYPOINTNAVIGATIONGOAL>"
   "DOWAYPOINTNAVIGATIONGOAL"
   "<DOWAYPOINTNAVIGATIONRESULT>"
   "DOWAYPOINTNAVIGATIONRESULT"
  ))

