; Auto-generated. Do not edit!


(cl:in-package pal_waypoint_msgs-msg)


;//! \htmlinclude DoWaypointNavigationResult.msg.html

(cl:defclass <DoWaypointNavigationResult> (roslisp-msg-protocol:ros-message)
  ((waypoints
    :reader waypoints
    :initarg :waypoints
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass DoWaypointNavigationResult (<DoWaypointNavigationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoWaypointNavigationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoWaypointNavigationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_waypoint_msgs-msg:<DoWaypointNavigationResult> is deprecated: use pal_waypoint_msgs-msg:DoWaypointNavigationResult instead.")))

(cl:ensure-generic-function 'waypoints-val :lambda-list '(m))
(cl:defmethod waypoints-val ((m <DoWaypointNavigationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pal_waypoint_msgs-msg:waypoints-val is deprecated.  Use pal_waypoint_msgs-msg:waypoints instead.")
  (waypoints m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoWaypointNavigationResult>) ostream)
  "Serializes a message object of type '<DoWaypointNavigationResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'waypoints))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'waypoints))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoWaypointNavigationResult>) istream)
  "Deserializes a message object of type '<DoWaypointNavigationResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'waypoints) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'waypoints)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoWaypointNavigationResult>)))
  "Returns string type for a message object of type '<DoWaypointNavigationResult>"
  "pal_waypoint_msgs/DoWaypointNavigationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoWaypointNavigationResult)))
  "Returns string type for a message object of type 'DoWaypointNavigationResult"
  "pal_waypoint_msgs/DoWaypointNavigationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoWaypointNavigationResult>)))
  "Returns md5sum for a message object of type '<DoWaypointNavigationResult>"
  "a99b9a3e28048e5a6aa5336280edec75")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoWaypointNavigationResult)))
  "Returns md5sum for a message object of type 'DoWaypointNavigationResult"
  "a99b9a3e28048e5a6aa5336280edec75")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoWaypointNavigationResult>)))
  "Returns full string definition for message of type '<DoWaypointNavigationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Waypoints reached successfully, by index inside the group parameter~%int32[] waypoints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoWaypointNavigationResult)))
  "Returns full string definition for message of type 'DoWaypointNavigationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Waypoints reached successfully, by index inside the group parameter~%int32[] waypoints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoWaypointNavigationResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'waypoints) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoWaypointNavigationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DoWaypointNavigationResult
    (cl:cons ':waypoints (waypoints msg))
))
