// Generated by gencpp from file pal_waypoint_msgs/DoWaypointNavigationActionGoal.msg
// DO NOT EDIT!


#ifndef PAL_WAYPOINT_MSGS_MESSAGE_DOWAYPOINTNAVIGATIONACTIONGOAL_H
#define PAL_WAYPOINT_MSGS_MESSAGE_DOWAYPOINTNAVIGATIONACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <pal_waypoint_msgs/DoWaypointNavigationGoal.h>

namespace pal_waypoint_msgs
{
template <class ContainerAllocator>
struct DoWaypointNavigationActionGoal_
{
  typedef DoWaypointNavigationActionGoal_<ContainerAllocator> Type;

  DoWaypointNavigationActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  DoWaypointNavigationActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::pal_waypoint_msgs::DoWaypointNavigationGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoWaypointNavigationActionGoal_

typedef ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<std::allocator<void> > DoWaypointNavigationActionGoal;

typedef boost::shared_ptr< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal > DoWaypointNavigationActionGoalPtr;
typedef boost::shared_ptr< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal const> DoWaypointNavigationActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator1> & lhs, const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator1> & lhs, const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_waypoint_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0033e8fdb0b46b89edf7cd427fe9cf2f";
  }

  static const char* value(const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0033e8fdb0b46b89ULL;
  static const uint64_t static_value2 = 0xedf7cd427fe9cf2fULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_waypoint_msgs/DoWaypointNavigationActionGoal";
  }

  static const char* value(const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"DoWaypointNavigationGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pal_waypoint_msgs/DoWaypointNavigationGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Group of the waypoints\n"
"string group\n"
"\n"
"# Start navigation from first_wp\n"
"uint32 first_wp\n"
"\n"
"# Number of waypoints to visit, 0 means all \n"
"int32 num_wp\n"
"\n"
"#If a point in the waypoint group fails, ignore and continue to next one\n"
"bool continue_on_error\n"
;
  }

  static const char* value(const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoWaypointNavigationActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_waypoint_msgs::DoWaypointNavigationActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::pal_waypoint_msgs::DoWaypointNavigationGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_WAYPOINT_MSGS_MESSAGE_DOWAYPOINTNAVIGATIONACTIONGOAL_H
