// Generated by gencpp from file pal_startup_msgs/StartupGetLogFile.msg
// DO NOT EDIT!


#ifndef PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGFILE_H
#define PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGFILE_H

#include <ros/service_traits.h>


#include <pal_startup_msgs/StartupGetLogFileRequest.h>
#include <pal_startup_msgs/StartupGetLogFileResponse.h>


namespace pal_startup_msgs
{

struct StartupGetLogFile
{

typedef StartupGetLogFileRequest Request;
typedef StartupGetLogFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartupGetLogFile
} // namespace pal_startup_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_startup_msgs::StartupGetLogFile > {
  static const char* value()
  {
    return "ccb1bd5394209c4a6d7f5a5e0db3dd26";
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogFile&) { return value(); }
};

template<>
struct DataType< ::pal_startup_msgs::StartupGetLogFile > {
  static const char* value()
  {
    return "pal_startup_msgs/StartupGetLogFile";
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogFile&) { return value(); }
};


// service_traits::MD5Sum< ::pal_startup_msgs::StartupGetLogFileRequest> should match
// service_traits::MD5Sum< ::pal_startup_msgs::StartupGetLogFile >
template<>
struct MD5Sum< ::pal_startup_msgs::StartupGetLogFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_startup_msgs::StartupGetLogFile >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupGetLogFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_startup_msgs::StartupGetLogFileRequest> should match
// service_traits::DataType< ::pal_startup_msgs::StartupGetLogFile >
template<>
struct DataType< ::pal_startup_msgs::StartupGetLogFileRequest>
{
  static const char* value()
  {
    return DataType< ::pal_startup_msgs::StartupGetLogFile >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupGetLogFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_startup_msgs::StartupGetLogFileResponse> should match
// service_traits::MD5Sum< ::pal_startup_msgs::StartupGetLogFile >
template<>
struct MD5Sum< ::pal_startup_msgs::StartupGetLogFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_startup_msgs::StartupGetLogFile >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupGetLogFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_startup_msgs::StartupGetLogFileResponse> should match
// service_traits::DataType< ::pal_startup_msgs::StartupGetLogFile >
template<>
struct DataType< ::pal_startup_msgs::StartupGetLogFileResponse>
{
  static const char* value()
  {
    return DataType< ::pal_startup_msgs::StartupGetLogFile >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupGetLogFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGFILE_H
