// Generated by gencpp from file pal_startup_msgs/StartupGetLogFileRequest.msg
// DO NOT EDIT!


#ifndef PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGFILEREQUEST_H
#define PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGFILEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_startup_msgs
{
template <class ContainerAllocator>
struct StartupGetLogFileRequest_
{
  typedef StartupGetLogFileRequest_<ContainerAllocator> Type;

  StartupGetLogFileRequest_()
    : app()  {
    }
  StartupGetLogFileRequest_(const ContainerAllocator& _alloc)
    : app(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _app_type;
  _app_type app;





  typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartupGetLogFileRequest_

typedef ::pal_startup_msgs::StartupGetLogFileRequest_<std::allocator<void> > StartupGetLogFileRequest;

typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogFileRequest > StartupGetLogFileRequestPtr;
typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogFileRequest const> StartupGetLogFileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator1> & lhs, const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator2> & rhs)
{
  return lhs.app == rhs.app;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator1> & lhs, const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_startup_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95ebb8aaf007b41ba941fcd0718c5693";
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95ebb8aaf007b41bULL;
  static const uint64_t static_value2 = 0xa941fcd0718c5693ULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_startup_msgs/StartupGetLogFileRequest";
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string app\n"
;
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.app);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartupGetLogFileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_startup_msgs::StartupGetLogFileRequest_<ContainerAllocator>& v)
  {
    s << indent << "app: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.app);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGFILEREQUEST_H
