// Generated by gencpp from file pal_startup_msgs/StartupStart.msg
// DO NOT EDIT!


#ifndef PAL_STARTUP_MSGS_MESSAGE_STARTUPSTART_H
#define PAL_STARTUP_MSGS_MESSAGE_STARTUPSTART_H

#include <ros/service_traits.h>


#include <pal_startup_msgs/StartupStartRequest.h>
#include <pal_startup_msgs/StartupStartResponse.h>


namespace pal_startup_msgs
{

struct StartupStart
{

typedef StartupStartRequest Request;
typedef StartupStartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartupStart
} // namespace pal_startup_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_startup_msgs::StartupStart > {
  static const char* value()
  {
    return "9b78b04bdfab704be898cd6637524866";
  }

  static const char* value(const ::pal_startup_msgs::StartupStart&) { return value(); }
};

template<>
struct DataType< ::pal_startup_msgs::StartupStart > {
  static const char* value()
  {
    return "pal_startup_msgs/StartupStart";
  }

  static const char* value(const ::pal_startup_msgs::StartupStart&) { return value(); }
};


// service_traits::MD5Sum< ::pal_startup_msgs::StartupStartRequest> should match
// service_traits::MD5Sum< ::pal_startup_msgs::StartupStart >
template<>
struct MD5Sum< ::pal_startup_msgs::StartupStartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_startup_msgs::StartupStart >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupStartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_startup_msgs::StartupStartRequest> should match
// service_traits::DataType< ::pal_startup_msgs::StartupStart >
template<>
struct DataType< ::pal_startup_msgs::StartupStartRequest>
{
  static const char* value()
  {
    return DataType< ::pal_startup_msgs::StartupStart >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupStartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_startup_msgs::StartupStartResponse> should match
// service_traits::MD5Sum< ::pal_startup_msgs::StartupStart >
template<>
struct MD5Sum< ::pal_startup_msgs::StartupStartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_startup_msgs::StartupStart >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupStartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_startup_msgs::StartupStartResponse> should match
// service_traits::DataType< ::pal_startup_msgs::StartupStart >
template<>
struct DataType< ::pal_startup_msgs::StartupStartResponse>
{
  static const char* value()
  {
    return DataType< ::pal_startup_msgs::StartupStart >::value();
  }
  static const char* value(const ::pal_startup_msgs::StartupStartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_STARTUP_MSGS_MESSAGE_STARTUPSTART_H
