// Generated by gencpp from file pal_startup_msgs/StartupGetLogResponse.msg
// DO NOT EDIT!


#ifndef PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGRESPONSE_H
#define PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pal_startup_msgs
{
template <class ContainerAllocator>
struct StartupGetLogResponse_
{
  typedef StartupGetLogResponse_<ContainerAllocator> Type;

  StartupGetLogResponse_()
    : log()  {
    }
  StartupGetLogResponse_(const ContainerAllocator& _alloc)
    : log(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _log_type;
  _log_type log;





  typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartupGetLogResponse_

typedef ::pal_startup_msgs::StartupGetLogResponse_<std::allocator<void> > StartupGetLogResponse;

typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogResponse > StartupGetLogResponsePtr;
typedef boost::shared_ptr< ::pal_startup_msgs::StartupGetLogResponse const> StartupGetLogResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator1> & lhs, const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator2> & rhs)
{
  return lhs.log == rhs.log;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator1> & lhs, const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_startup_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3e2a6f3c8b4a69b39bb08b44fadcdca";
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3e2a6f3c8b4a69bULL;
  static const uint64_t static_value2 = 0x39bb08b44fadcdcaULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_startup_msgs/StartupGetLogResponse";
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string log\n"
"\n"
;
  }

  static const char* value(const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.log);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartupGetLogResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_startup_msgs::StartupGetLogResponse_<ContainerAllocator>& v)
  {
    s << indent << "log: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.log);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_STARTUP_MSGS_MESSAGE_STARTUPGETLOGRESPONSE_H
