(cl:defpackage pal_startup_msgs-srv
  (:use )
  (:export
   "STARTUPGETLOG"
   "<STARTUPGETLOG-REQUEST>"
   "STARTUPGETLOG-REQUEST"
   "<STARTUPGETLOG-RESPONSE>"
   "STARTUPGETLOG-RESPONSE"
   "STARTUPGETLOGFILE"
   "<STARTUPGETLOGFILE-REQUEST>"
   "STARTUPGETLOGFILE-REQUEST"
   "<STARTUPGETLOGFILE-RESPONSE>"
   "STARTUPGETLOGFILE-RESPONSE"
   "STARTUPSTART"
   "<STARTUPSTART-REQUEST>"
   "STARTUPSTART-REQUEST"
   "<STARTUPSTART-RESPONSE>"
   "STARTUPSTART-RESPONSE"
   "STARTUPSTOP"
   "<STARTUPSTOP-REQUEST>"
   "STARTUPSTOP-REQUEST"
   "<STARTUPSTOP-RESPONSE>"
   "STARTUPSTOP-RESPONSE"
  ))

