; Auto-generated. Do not edit!


(cl:in-package mm11_msgs-msg)


;//! \htmlinclude DisplayFeedback.msg.html

(cl:defclass <DisplayFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DisplayFeedback (<DisplayFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DisplayFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DisplayFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mm11_msgs-msg:<DisplayFeedback> is deprecated: use mm11_msgs-msg:DisplayFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DisplayFeedback>) ostream)
  "Serializes a message object of type '<DisplayFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DisplayFeedback>) istream)
  "Deserializes a message object of type '<DisplayFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DisplayFeedback>)))
  "Returns string type for a message object of type '<DisplayFeedback>"
  "mm11_msgs/DisplayFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DisplayFeedback)))
  "Returns string type for a message object of type 'DisplayFeedback"
  "mm11_msgs/DisplayFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DisplayFeedback>)))
  "Returns md5sum for a message object of type '<DisplayFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DisplayFeedback)))
  "Returns md5sum for a message object of type 'DisplayFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DisplayFeedback>)))
  "Returns full string definition for message of type '<DisplayFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DisplayFeedback)))
  "Returns full string definition for message of type 'DisplayFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DisplayFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DisplayFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DisplayFeedback
))
