# Generated by Django 4.2.27 on 2025-12-04 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('postura', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('pulso', models.IntegerField()),
                ('fuerza', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
