# Generated by Django 4.2.27 on 2025-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0002_resultadosesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadosesion',
            old_name='postura',
            new_name='reflejos',
        ),
        migrations.RemoveField(
            model_name='resultadosesion',
            name='fuerza',
        ),
        migrations.AddField(
            model_name='resultadosesion',
            name='postura_cadera',
            field=models.CharField(default='Sin evaluar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosesion',
            name='postura_hombros',
            field=models.CharField(default='Sin evaluar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosesion',
            name='postura_torso',
            field=models.CharField(default='Sin evaluar', max_length=50),
            preserve_default=False,
        ),
    ]
