# Generated by Django 4.2.27 on 2025-12-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0003_rename_postura_resultadosesion_reflejos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosesion',
            name='pulso',
            field=models.CharField(max_length=64),
        ),
    ]
