(cl:defpackage amcl-srv
  (:use )
  (:export
   "RANDOMIZE"
   "<RANDOMIZE-REQUEST>"
   "RANDOMIZE-REQUEST"
   "<RANDOMIZE-RESPONSE>"
   "RANDOMIZE-RESPONSE"
   "SETINITIALPOSE"
   "<SETINITIALPOSE-REQUEST>"
   "SETINITIALPOSE-REQUEST"
   "<SETINITIALPOSE-RESPONSE>"
   "SETINITIALPOSE-RESPONSE"
  ))

