string appName #Name of the application 
---
# Possible levels of operations
byte OK=0
byte WARN=1
byte ERROR=2
byte STALE=3 #Application not running
byte level # level of operation enumerated above 
