(cl:defpackage corridor_exploration_msgs-msg
  (:use )
  (:export
   "<CORRIDOREXPLORATIONACTION>"
   "CORRIDOREXPLORATIONACTION"
   "<CORRIDOREXPLORATIONACTIONFEEDBACK>"
   "CORRIDOREXPLORATIONACTIONFEEDBACK"
   "<CORRIDOREXPLORATIONACTIONGOAL>"
   "CORRIDOREXPLORATIONACTIONGOAL"
   "<CORRIDOREXPLORATIONACTIONRESULT>"
   "CORRIDOREXPLORATIONACTIONRESULT"
   "<CORRIDOREXPLORATIONFEEDBACK>"
   "CORRIDOREXPLORATIONFEEDBACK"
   "<CORRIDOREXPLORATIONGOAL>"
   "CORRIDOREXPLORATIONGOAL"
   "<CORRIDOREXPLORATIONRESULT>"
   "CORRIDOREXPLORATIONRESULT"
  ))

