; Auto-generated. Do not edit!


(cl:in-package corridor_exploration_msgs-msg)


;//! \htmlinclude CorridorExplorationResult.msg.html

(cl:defclass <CorridorExplorationResult> (roslisp-msg-protocol:ros-message)
  ((reached
    :reader reached
    :initarg :reached
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool))
   (message
    :reader message
    :initarg :message
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass CorridorExplorationResult (<CorridorExplorationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CorridorExplorationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CorridorExplorationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name corridor_exploration_msgs-msg:<CorridorExplorationResult> is deprecated: use corridor_exploration_msgs-msg:CorridorExplorationResult instead.")))

(cl:ensure-generic-function 'reached-val :lambda-list '(m))
(cl:defmethod reached-val ((m <CorridorExplorationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader corridor_exploration_msgs-msg:reached-val is deprecated.  Use corridor_exploration_msgs-msg:reached instead.")
  (reached m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <CorridorExplorationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader corridor_exploration_msgs-msg:message-val is deprecated.  Use corridor_exploration_msgs-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CorridorExplorationResult>) ostream)
  "Serializes a message object of type '<CorridorExplorationResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'reached) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'message) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CorridorExplorationResult>) istream)
  "Deserializes a message object of type '<CorridorExplorationResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'reached) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'message) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CorridorExplorationResult>)))
  "Returns string type for a message object of type '<CorridorExplorationResult>"
  "corridor_exploration_msgs/CorridorExplorationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CorridorExplorationResult)))
  "Returns string type for a message object of type 'CorridorExplorationResult"
  "corridor_exploration_msgs/CorridorExplorationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CorridorExplorationResult>)))
  "Returns md5sum for a message object of type '<CorridorExplorationResult>"
  "7d210301fb84a541ab3ae1d0d10f9358")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CorridorExplorationResult)))
  "Returns md5sum for a message object of type 'CorridorExplorationResult"
  "7d210301fb84a541ab3ae1d0d10f9358")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CorridorExplorationResult>)))
  "Returns full string definition for message of type '<CorridorExplorationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Bool reached~%std_msgs/String message~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CorridorExplorationResult)))
  "Returns full string definition for message of type 'CorridorExplorationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Bool reached~%std_msgs/String message~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CorridorExplorationResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'reached))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CorridorExplorationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CorridorExplorationResult
    (cl:cons ':reached (reached msg))
    (cl:cons ':message (message msg))
))
